[package]
name = "util"
version = "0.1.0"
authors = ["Ben Collins <aggieben@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.1.0"
nom = "5.0.1"
log = "0.4.8"
pretty_env_logger = "0.3.1"